# Generated by Django 3.0.6 on 2020-05-14 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('field_name', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('field_name', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service_CI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_id', models.IntegerField(default=0)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('portfolio', models.TextField()),
                ('sub_portfolio', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Owner')),
            ],
        ),
    ]
