# Generated by Django 3.0.6 on 2020-07-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together={('metric', 'date_begin', 'date_end')},
        ),
    ]
