# Generated by Django 3.0.6 on 2020-05-14 11:59

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_owner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phone_field.models.PhoneField(default=1, max_length=31),
            preserve_default=False,
        ),
    ]
