# Generated by Django 3.0.6 on 2020-05-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='field_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='field_name',
            new_name='email',
        ),
    ]
