# Generated by Django 3.0.6 on 2020-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200720_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetricvalueregistration',
            name='date_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalmetricvalueregistration',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='metricvalueregistration',
            name='date_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='metricvalueregistration',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
