# Generated by Django 3.0.6 on 2020-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200618_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetricvalue',
            name='value',
            field=models.IntegerField(verbose_name='Metric value'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value',
            field=models.IntegerField(verbose_name='Metric value'),
        ),
    ]
