# Generated by Django 3.0.6 on 2020-05-14 12:54

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200514_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='service_ci',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='app1.Staff'),
        ),
        migrations.AlterField(
            model_name='service_ci',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app1.Staff'),
        ),
    ]
