# Generated by Django 3.0.6 on 2020-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200514_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
