# Generated by Django 3.0.6 on 2020-07-23 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200720_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ALERT', 'ALERT')], default='INFO', max_length=30)),
                ('text', models.TextField(verbose_name='Content')),
                ('subject', models.CharField(max_length=100)),
                ('recipientList', models.TextField(verbose_name='To')),
                ('status', models.FloatField(blank=True, null=True, verbose_name='Delivery status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'User notification',
            },
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='alerts_on',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Alerts on'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='notification_on',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Notification on'),
        ),
        migrations.AddField(
            model_name='service',
            name='alerts_on',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Alerts on'),
        ),
        migrations.AddField(
            model_name='service',
            name='notification_on',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Notification on'),
        ),
    ]
