# Generated by Django 3.0.6 on 2020-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200514_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
