# Generated by Django 3.0.6 on 2020-05-21 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0009_historicalservice_ci_historicalstaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalService_CI',
            new_name='HistoricalService',
        ),
        migrations.RenameModel(
            old_name='Service_CI',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='historicalservice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical service'},
        ),
    ]
