# Generated by Django 3.0.6 on 2020-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200522_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='design_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='portfolio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='sub_portfolio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='design_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='portfolio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_portfolio',
            field=models.CharField(max_length=50),
        ),
    ]
