# Generated by Django 3.0.6 on 2020-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200525_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstaff',
            name='table_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='table_number',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='status',
            field=models.CharField(choices=[('DEF', 'Defined'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='DEF', max_length=4),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('DEF', 'Defined'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='DEF', max_length=4),
        ),
    ]
