# Generated by Django 3.0.6 on 2020-05-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200527_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='status',
            field=models.CharField(choices=[('DEF', 'Defined'), ('SUB', 'Submited'), ('DEP', 'DEPLOYED'), ('OP', 'Operational'), ('RETU', 'Retired(Upgrade)'), ('RETR', 'Retired(Replacemenet)'), ('RETO', 'Retired(Obsolete)'), ('CANU', 'Cancelled(Upgrade)'), ('CANR', 'Cancelled(Replacemenet)'), ('EXT', 'External premises'), ('UNCO', 'Under consideration'), ('UNK', 'Unknown'), ('DIS', 'Displaced'), ('NA', 'Not agreed')], default='DEF', max_length=4),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('DEF', 'Defined'), ('SUB', 'Submited'), ('DEP', 'DEPLOYED'), ('OP', 'Operational'), ('RETU', 'Retired(Upgrade)'), ('RETR', 'Retired(Replacemenet)'), ('RETO', 'Retired(Obsolete)'), ('CANU', 'Cancelled(Upgrade)'), ('CANR', 'Cancelled(Replacemenet)'), ('EXT', 'External premises'), ('UNCO', 'Under consideration'), ('UNK', 'Unknown'), ('DIS', 'Displaced'), ('NA', 'Not agreed')], default='DEF', max_length=4),
        ),
    ]
