# Generated by Django 3.0.6 on 2020-05-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0019_auto_20200527_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('DEF', 'Defined'), ('SUB', 'Submited'), ('DEP', 'Deployed'), ('OP', 'Operational'), ('RETU', 'Retired(Upgrade)'), ('RETR', 'Retired(Replacemenet)'), ('RETO', 'Retired(Obsolete)'), ('CANU', 'Cancelled(Upgrade)'), ('CANR', 'Cancelled(Replacemenet)'), ('EXT', 'External premises'), ('UNCO', 'Under consideration'), ('UNK', 'Unknown'), ('DIS', 'Displaced'), ('NA', 'Not agreed')], default='DEF', max_length=4)),
                ('metric_order', models.IntegerField()),
                ('nature', models.CharField(max_length=300)),
                ('regularity', models.CharField(max_length=300)),
                ('obt_deadline', models.CharField(max_length=300)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Service')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMetric',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('DEF', 'Defined'), ('SUB', 'Submited'), ('DEP', 'Deployed'), ('OP', 'Operational'), ('RETU', 'Retired(Upgrade)'), ('RETR', 'Retired(Replacemenet)'), ('RETO', 'Retired(Obsolete)'), ('CANU', 'Cancelled(Upgrade)'), ('CANR', 'Cancelled(Replacemenet)'), ('EXT', 'External premises'), ('UNCO', 'Under consideration'), ('UNK', 'Unknown'), ('DIS', 'Displaced'), ('NA', 'Not agreed')], default='DEF', max_length=4)),
                ('metric_order', models.IntegerField()),
                ('nature', models.CharField(max_length=300)),
                ('regularity', models.CharField(max_length=300)),
                ('obt_deadline', models.CharField(max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app1.Service')),
            ],
            options={
                'verbose_name': 'historical metric',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
