# Generated by Django 3.0.6 on 2020-05-27 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_historicalmetric_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Metric')),
            ],
        ),
    ]
