# Generated by Django 3.0.6 on 2020-05-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_historicalmeasurement_historicalvalue'),
        ('app1', '0015_auto_20200525_1548'),
    ]

    operations = [
    ]
