# Generated by Django 3.0.6 on 2020-05-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_merge_20200528_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='portfolio',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='sub_portfolio',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='portfolio',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_portfolio',
            field=models.CharField(max_length=250),
        ),
    ]
