# Generated by Django 3.0.6 on 2020-05-29 12:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20200528_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstaff',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='historicalstaff',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='surname',
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
