# Generated by Django 3.0.6 on 2020-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20200529_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='totalorder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='totalorder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
