# Generated by Django 3.0.6 on 2020-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20200601_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmetric',
            name='obt_deadline',
        ),
        migrations.RemoveField(
            model_name='historicalmetric',
            name='regularity',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='obt_deadline',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='regularity',
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='measr_regularity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='publ_deadline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='publ_regularity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='metric',
            name='measr_regularity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='metric',
            name='publ_deadline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='metric',
            name='publ_regularity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
