# Generated by Django 3.0.6 on 2020-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20200602_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='totalorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='totalorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total order'),
        ),
    ]
