# Generated by Django 3.0.6 on 2020-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20200602_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetricvalue',
            name='metric_value',
            field=models.IntegerField(default=0, verbose_name='Metric value'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='metric_value',
            field=models.IntegerField(default=0, verbose_name='Metric value'),
        ),
    ]
