# Generated by Django 3.0.6 on 2020-06-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20200602_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmetricvalue',
            old_name='metric_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='metricvalue',
            old_name='metric_value',
            new_name='value',
        ),
    ]
