# Generated by Django 3.0.6 on 2020-06-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20200602_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmetricvalue',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Metric value'},
        ),
        migrations.AlterModelOptions(
            name='metricvalue',
            options={'verbose_name': 'Metric value'},
        ),
    ]
