# Generated by Django 3.0.6 on 2020-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20200603_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetric',
            name='date_begin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='date_begin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
