# Generated by Django 3.0.6 on 2020-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20200612_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetric',
            name='date_begin',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='date_end',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='date_begin',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='date_end',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
