# Generated by Django 3.0.6 on 2020-06-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20200612_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricvalue',
            name='metric',
            field=models.ForeignKey(blank=0, on_delete=django.db.models.deletion.PROTECT, to='app1.Metric'),
        ),
    ]
