# Generated by Django 3.0.6 on 2020-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20200616_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetric',
            name='mtrc_design_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='mtrc_design_id',
            field=models.IntegerField(default=0),
        ),
    ]
