# Generated by Django 3.0.6 on 2020-06-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20200616_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmetric',
            old_name='mtrc_design_id',
            new_name='design_id',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='mtrc_design_id',
            new_name='design_id',
        ),
    ]
